[tool.poetry]
package-mode = false

[project]
name = "file-converter-app"
version = "0.1.0"
description = "XPT â†” Parquet â†” CSV converter Streamlit app"
requires-python = ">=3.9"

dependencies = [
    "streamlit",
    "pandas",
    "pyarrow",
    "pyreadstat"
]

[tool.streamlit]
serverPort = 8501